/**
 * @fileoverview Gemini request body types.
 * @see https://ai.google.dev/gemini-api/docs Gemini
 * @see https://ai.google.dev/api/generate-content Gemini
 */

// --------------------------------------------------------------------------------
// Export
// --------------------------------------------------------------------------------

/**
 * JSON-compatible value used by flexible Gemini API fields such as schemas,
 * tool arguments, and tool responses.
 */
export type JSONValue =
  | string
  | number
  | boolean
  | null
  | JSONValue[]
  | {
      [key: string]: JSONValue;
    };

/**
 * JSON object map used by structured Gemini API fields.
 */
export type JSONObject = Record<string, JSONValue>;

/**
 * Request body accepted by Gemini `models.generateContent` and
 * `models.streamGenerateContent`.
 */
export type GeminiRequestBody =
  | GeminiGenerateContentRequestBody
  | GeminiStreamGenerateContentRequestBody;

/**
 * Request body for `models.generateContent`.
 */
export interface GeminiGenerateContentRequestBody {
  /**
   * Current conversation content sent to the model.
   *
   * For a single-turn request this is usually one item. For multi-turn chat,
   * this contains the conversation history and the latest user message.
   */
  contents: GeminiContent[];

  /**
   * Tools the model may use to generate a response.
   */
  tools?: GeminiTool[];

  /**
   * Tool configuration used when tools are provided.
   */
  toolConfig?: GeminiToolConfig;

  /**
   * Safety settings that override the API defaults for their categories.
   */
  safetySettings?: GeminiSafetySetting[];

  /**
   * Developer-provided system instruction.
   *
   * The REST API currently supports text-only system instructions.
   */
  systemInstruction?: GeminiContent;

  /**
   * Model generation and output configuration.
   */
  generationConfig?: GeminiGenerationConfig;

  /**
   * Cached content resource name to use as prediction context.
   *
   * Format: `cachedContents/{cachedContent}`.
   */
  cachedContent?: string;

  /**
   * Service tier for the request.
   *
   * @default 'unspecified'
   */
  serviceTier?: GeminiServiceTier;

  /**
   * Per-request logging behavior override.
   */
  store?: boolean;
}

/**
 * Request body for `models.streamGenerateContent`.
 *
 * The streaming method accepts the same `GenerateContentRequest` body as
 * `models.generateContent`.
 */
export type GeminiStreamGenerateContentRequestBody = GeminiGenerateContentRequestBody;

/**
 * Multi-part message content in a Gemini conversation.
 */
export interface GeminiContent {
  /**
   * Ordered parts that make up a single message.
   */
  parts: GeminiPart[];

  /**
   * Producer of this content.
   *
   * Useful for multi-turn conversations; single-turn requests can omit it.
   */
  role?: 'user' | 'model';
}

/**
 * One media or structured data part within a `GeminiContent` message.
 *
 * A part can contain only one accepted data field.
 */
export type GeminiPart = GeminiPartBase &
  (
    | {
        /**
         * Inline text content.
         */
        text: string;
      }
    | {
        /**
         * Inline media bytes.
         */
        inlineData: GeminiBlob;
      }
    | {
        /**
         * Function call predicted by the model.
         */
        functionCall: GeminiFunctionCall;
      }
    | {
        /**
         * Function call result supplied back to the model.
         */
        functionResponse: GeminiFunctionResponse;
      }
    | {
        /**
         * URI-based file data.
         */
        fileData: GeminiFileData;
      }
    | {
        /**
         * Code generated by the model for code execution.
         */
        executableCode: GeminiExecutableCode;
      }
    | {
        /**
         * Result of executing model-generated code.
         */
        codeExecutionResult: GeminiCodeExecutionResult;
      }
    | {
        /**
         * Server-side tool call predicted by the model.
         */
        toolCall: GeminiToolCall;
      }
    | {
        /**
         * Server-side tool result supplied back to the model.
         */
        toolResponse: GeminiToolResponse;
      }
  );

/**
 * Shared metadata fields available on every Gemini part.
 */
export interface GeminiPartBase {
  /**
   * Whether this part is a model thought.
   */
  thought?: boolean;

  /**
   * Opaque base64 signature for reusing a thought in later requests.
   */
  thoughtSignature?: string;

  /**
   * Custom metadata for clients that need to track extra part information.
   */
  partMetadata?: JSONObject;

  /**
   * Media resolution for input media.
   */
  mediaResolution?: GeminiPartMediaResolution;

  /**
   * Deprecated video metadata.
   *
   * @deprecated Use the current generate content processing options instead.
   */
  videoMetadata?: GeminiVideoMetadata;
}

/**
 * Deprecated video preprocessing metadata for a `GeminiPart`.
 *
 * @deprecated Use the current generate content processing options instead.
 */
export interface GeminiVideoMetadata {
  /**
   * Start offset of the video as a protobuf duration string.
   */
  startOffset?: string;

  /**
   * End offset of the video as a protobuf duration string.
   */
  endOffset?: string;

  /**
   * Frame rate of the video sent to the model.
   *
   * @default 1.0
   */
  fps?: number;
}

/**
 * Raw inline media bytes.
 */
export interface GeminiBlob {
  /**
   * IANA MIME type of the source data.
   */
  mimeType: string;

  /**
   * Base64-encoded raw media bytes.
   */
  data: string;
}

/**
 * Function call predicted by the model.
 */
export interface GeminiFunctionCall {
  /**
   * Optional unique function call identifier.
   */
  id?: string;

  /**
   * Function name to call.
   */
  name: string;

  /**
   * Function arguments in JSON object format.
   */
  args?: JSONObject;
}

/**
 * Function execution result returned to the model.
 */
export interface GeminiFunctionResponse {
  /**
   * Identifier of the function call this response belongs to.
   */
  id?: string;

  /**
   * Function name matching the function call.
   */
  name: string;

  /**
   * Function response payload in JSON object format.
   */
  response: JSONObject;

  /**
   * Ordered media parts that make up the function response.
   */
  parts?: GeminiFunctionResponsePart[];

  /**
   * Whether more responses will be returned for a non-blocking function call.
   */
  willContinue?: boolean;

  /**
   * How the function response should be scheduled in the conversation.
   *
   * @default 'WHEN_IDLE'
   */
  scheduling?: 'SCHEDULING_UNSPECIFIED' | 'SILENT' | 'WHEN_IDLE' | 'INTERRUPT';
}

/**
 * Media data part within a `GeminiFunctionResponse`.
 */
export interface GeminiFunctionResponsePart {
  /**
   * Inline media bytes for the function response.
   */
  inlineData: GeminiFunctionResponseBlob;
}

/**
 * Raw media bytes for a function response.
 */
export interface GeminiFunctionResponseBlob {
  /**
   * IANA MIME type of the source data.
   */
  mimeType: string;

  /**
   * Base64-encoded raw media bytes.
   */
  data: string;
}

/**
 * URI-based file data.
 */
export interface GeminiFileData {
  /**
   * IANA MIME type of the source data.
   */
  mimeType?: string;

  /**
   * File URI.
   */
  fileUri: string;
}

/**
 * Code generated by the model for the Code Execution tool.
 */
export interface GeminiExecutableCode {
  /**
   * Optional unique executable code identifier.
   */
  id?: string;

  /**
   * Programming language of the code.
   *
   * @default 'PYTHON'
   */
  language: 'LANGUAGE_UNSPECIFIED' | 'PYTHON';

  /**
   * Code to execute.
   */
  code: string;
}

/**
 * Result of executing `GeminiExecutableCode`.
 */
export interface GeminiCodeExecutionResult {
  /**
   * Identifier of the executable code part this result belongs to.
   */
  id?: string;

  /**
   * Code execution outcome.
   */
  outcome:
    | 'OUTCOME_UNSPECIFIED'
    | 'OUTCOME_OK'
    | 'OUTCOME_FAILED'
    | 'OUTCOME_DEADLINE_EXCEEDED';

  /**
   * Standard output for success, or stderr/diagnostic text otherwise.
   */
  output?: string;
}

/**
 * Server-side tool call predicted by the model.
 */
export interface GeminiToolCall {
  /**
   * Optional unique tool call identifier.
   */
  id?: string;

  /**
   * Type of tool that was called.
   */
  toolType: GeminiToolType;

  /**
   * Tool call arguments.
   */
  args?: JSONObject;
}

/**
 * Server-side tool response returned to the model.
 */
export interface GeminiToolResponse {
  /**
   * Identifier of the tool call this response belongs to.
   */
  id?: string;

  /**
   * Tool type matching the corresponding tool call.
   */
  toolType: GeminiToolType;

  /**
   * Tool response payload.
   */
  response?: JSONObject;
}

/**
 * Server-side tool types used by `GeminiToolCall` and `GeminiToolResponse`.
 */
export type GeminiToolType =
  | 'TOOL_TYPE_UNSPECIFIED'
  | 'GOOGLE_SEARCH_WEB'
  | 'GOOGLE_SEARCH_IMAGE'
  | 'URL_CONTEXT'
  | 'GOOGLE_MAPS'
  | 'FILE_SEARCH';

/**
 * Tool definition made available to the model.
 */
export interface GeminiTool {
  /**
   * Client-executed function declarations available to the model.
   */
  functionDeclarations?: GeminiFunctionDeclaration[];

  /**
   * Google Search retrieval grounding tool.
   */
  googleSearchRetrieval?: {
    /**
     * Dynamic retrieval behavior for the search source.
     */
    dynamicRetrievalConfig?: {
      /**
       * Dynamic retrieval mode.
       */
      mode?: 'MODE_UNSPECIFIED' | 'MODE_DYNAMIC';

      /**
       * Threshold for dynamic retrieval.
       *
       * @default system-defined
       */
      dynamicThreshold?: number;
    };
  };

  /**
   * Enables automatic execution of model-generated code.
   */
  codeExecution?: Record<string, never>;

  /**
   * Google Search tool.
   */
  googleSearch?: {
    /**
     * Filter search results to a time interval.
     */
    timeRangeFilter?: {
      /**
       * Inclusive RFC 3339 interval start time.
       */
      startTime?: string;

      /**
       * Exclusive RFC 3339 interval end time.
       */
      endTime?: string;
    };

    /**
     * Search types to enable.
     *
     * @default { webSearch: {} }
     */
    searchTypes?: {
      /**
       * Enable web search.
       */
      webSearch?: Record<string, never>;

      /**
       * Enable image search.
       */
      imageSearch?: Record<string, never>;
    };
  };

  /**
   * Computer-use tool configuration.
   */
  computerUse?: GeminiComputerUse;

  /**
   * URL context retrieval tool.
   */
  urlContext?: Record<string, never>;

  /**
   * File search tool for retrieval from file search stores.
   */
  fileSearch?: {
    /**
     * File search store resource names.
     */
    fileSearchStoreNames: string[];

    /**
     * Metadata filter expression.
     */
    metadataFilter?: string;

    /**
     * Maximum number of retrieved results.
     */
    topK?: number;
  };

  /**
   * MCP servers the model may connect to.
   */
  mcpServers?: GeminiMcpServer[];

  /**
   * Google Maps grounding tool.
   */
  googleMaps?: {
    /**
     * Whether to include a widget context token in grounding metadata.
     */
    enableWidget?: boolean;
  };
}

/**
 * Function declaration made available as a model tool.
 */
export interface GeminiFunctionDeclaration {
  /**
   * Function name.
   */
  name: string;

  /**
   * Brief function description.
   */
  description: string;

  /**
   * Function behavior.
   *
   * @default 'BLOCKING'
   */
  behavior?: 'UNSPECIFIED' | 'BLOCKING' | 'NON_BLOCKING';

  /**
   * Function parameter schema.
   */
  parameters?: GeminiSchema;

  /**
   * Function parameter JSON Schema.
   */
  parametersJsonSchema?: JSONValue;

  /**
   * Function response schema.
   */
  response?: GeminiSchema;

  /**
   * Function response JSON Schema.
   */
  responseJsonSchema?: JSONValue;
}

/**
 * MCP server definition available to Gemini tools.
 */
export interface GeminiMcpServer {
  /**
   * MCP server name.
   */
  name: string;

  /**
   * Streamable HTTP transport configuration.
   */
  streamableHttpTransport: {
    /**
     * Full MCP endpoint URL.
     */
    url: string;

    /**
     * Optional authentication, timeout, or transport headers.
     */
    headers?: Record<string, string>;

    /**
     * HTTP timeout as a protobuf duration string.
     */
    timeout?: string;

    /**
     * SSE read timeout as a protobuf duration string.
     */
    sseReadTimeout?: string;

    /**
     * Whether to close the client session when the transport closes.
     */
    terminateOnClose?: boolean;
  };
}

/**
 * Computer-use tool configuration.
 */
export interface GeminiComputerUse {
  /**
   * Environment being operated.
   */
  environment: 'ENVIRONMENT_UNSPECIFIED' | 'ENVIRONMENT_BROWSER';

  /**
   * Predefined computer-use functions to exclude from the final model call.
   */
  excludedPredefinedFunctions?: string[];
}

/**
 * Configuration for tool use in a request.
 */
export interface GeminiToolConfig {
  /**
   * Function calling behavior.
   */
  functionCallingConfig?: {
    /**
     * Function calling execution mode.
     *
     * @default 'AUTO'
     */
    mode?: 'MODE_UNSPECIFIED' | 'AUTO' | 'ANY' | 'NONE' | 'VALIDATED';

    /**
     * Function names the model may call when the mode supports constraints.
     */
    allowedFunctionNames?: string[];
  };

  /**
   * Retrieval configuration.
   */
  retrievalConfig?: GeminiRetrievalConfig;

  /**
   * Whether to include server-side tool calls and responses in the response.
   */
  includeServerSideToolInvocations?: boolean;
}

/**
 * Retrieval configuration.
 */
export interface GeminiRetrievalConfig {
  /**
   * User location.
   */
  latLng?: GeminiLatLng;

  /**
   * User language code.
   */
  languageCode?: string;
}

/**
 * Latitude and longitude pair.
 */
export interface GeminiLatLng {
  /**
   * Latitude in degrees, in the range `[-90.0, +90.0]`.
   */
  latitude: number;

  /**
   * Longitude in degrees, in the range `[-180.0, +180.0]`.
   */
  longitude: number;
}

/**
 * Safety blocking setting for one harm category.
 */
export interface GeminiSafetySetting {
  /**
   * Harm category controlled by this setting.
   */
  category: GeminiHarmCategory;

  /**
   * Harm probability threshold at which content is blocked.
   */
  threshold: GeminiHarmBlockThreshold;
}

/**
 * Gemini safety harm categories.
 */
export type GeminiHarmCategory =
  | 'HARM_CATEGORY_UNSPECIFIED'
  | 'HARM_CATEGORY_DEROGATORY'
  | 'HARM_CATEGORY_TOXICITY'
  | 'HARM_CATEGORY_VIOLENCE'
  | 'HARM_CATEGORY_SEXUAL'
  | 'HARM_CATEGORY_MEDICAL'
  | 'HARM_CATEGORY_DANGEROUS'
  | 'HARM_CATEGORY_HARASSMENT'
  | 'HARM_CATEGORY_HATE_SPEECH'
  | 'HARM_CATEGORY_SEXUALLY_EXPLICIT'
  | 'HARM_CATEGORY_DANGEROUS_CONTENT'
  | 'HARM_CATEGORY_CIVIC_INTEGRITY';

/**
 * Harm blocking threshold for a safety setting.
 */
export type GeminiHarmBlockThreshold =
  | 'HARM_BLOCK_THRESHOLD_UNSPECIFIED'
  | 'BLOCK_LOW_AND_ABOVE'
  | 'BLOCK_MEDIUM_AND_ABOVE'
  | 'BLOCK_ONLY_HIGH'
  | 'BLOCK_NONE'
  | 'OFF';

/**
 * Model generation and output configuration.
 */
export interface GeminiGenerationConfig {
  /**
   * Character sequences that stop output generation.
   */
  stopSequences?: string[];

  /**
   * MIME type of generated candidate text.
   *
   * @default 'text/plain'
   */
  responseMimeType?: 'text/plain' | 'application/json' | 'text/x.enum' | string;

  /**
   * OpenAPI-like schema for generated candidate text.
   */
  responseSchema?: GeminiSchema;

  /**
   * Alternative JSON Schema for generated response output.
   */
  _responseJsonSchema?: JSONValue;

  /**
   * Internal JSON Schema detail for generated response output.
   */
  responseJsonSchema?: JSONValue;

  /**
   * Requested response modalities.
   *
   * @default ['TEXT']
   */
  responseModalities?: GeminiModality[];

  /**
   * Number of generated response candidates.
   *
   * @default 1
   */
  candidateCount?: number;

  /**
   * Maximum number of output tokens in a response candidate.
   *
   * @default model-specific
   */
  maxOutputTokens?: number;

  /**
   * Randomness of the output.
   *
   * Values can range from `0.0` to `2.0`.
   *
   * @default model-specific
   */
  temperature?: number;

  /**
   * Maximum cumulative probability considered during nucleus sampling.
   *
   * @default model-specific
   */
  topP?: number;

  /**
   * Maximum number of tokens considered during top-k sampling.
   *
   * @default model-specific
   */
  topK?: number;

  /**
   * Seed used by generation.
   */
  seed?: number;

  /**
   * Penalty applied based on whether a token has already appeared.
   */
  presencePenalty?: number;

  /**
   * Penalty applied based on how often a token has already appeared.
   */
  frequencyPenalty?: number;

  /**
   * Whether to include logprobs in the response.
   */
  responseLogprobs?: boolean;

  /**
   * Number of top logprobs to return at each decoding step.
   */
  logprobs?: number;

  /**
   * Whether to enable enhanced civic answers when supported by the model.
   */
  enableEnhancedCivicAnswers?: boolean;

  /**
   * Speech generation configuration.
   */
  speechConfig?: GeminiSpeechConfig;

  /**
   * Thinking feature configuration.
   */
  thinkingConfig?: GeminiThinkingConfig;

  /**
   * Image generation configuration.
   */
  imageConfig?: GeminiImageConfig;

  /**
   * Media resolution used for inputs when supported.
   */
  mediaResolution?: GeminiMediaResolution;
}

/**
 * Response modality requested from the model.
 */
export type GeminiModality = 'MODALITY_UNSPECIFIED' | 'TEXT' | 'IMAGE' | 'AUDIO';

/**
 * Speech generation and transcription configuration.
 */
export interface GeminiSpeechConfig {
  /**
   * Single-speaker voice configuration.
   */
  voiceConfig?: {
    /**
     * Prebuilt voice configuration.
     */
    prebuiltVoiceConfig: {
      /**
       * Name of the preset voice to use.
       */
      voiceName: string;
    };
  };

  /**
   * Multi-speaker voice configuration.
   */
  multiSpeakerVoiceConfig?: {
    /**
     * Enabled speaker voice configurations.
     */
    speakerVoiceConfigs: {
      /**
       * Speaker name, matching the prompt speaker name.
       */
      speaker: string;

      /**
       * Voice configuration for this speaker.
       */
      voiceConfig: {
        /**
         * Prebuilt voice configuration.
         */
        prebuiltVoiceConfig: {
          /**
           * Name of the preset voice to use.
           */
          voiceName: string;
        };
      };
    }[];
  };

  /**
   * BCP-47 language code configured for speech recognition or synthesis.
   */
  languageCode?: string;
}

/**
 * Configuration for Gemini thinking features.
 */
export interface GeminiThinkingConfig {
  /**
   * Whether thoughts should be returned when available.
   */
  includeThoughts?: boolean;

  /**
   * Number of thought tokens the model should generate.
   */
  thinkingBudget?: number;

  /**
   * Maximum depth of internal reasoning before producing a response.
   *
   * Recommended for Gemini 3 or later models.
   *
   * @default 'HIGH'
   */
  thinkingLevel?: 'THINKING_LEVEL_UNSPECIFIED' | 'MINIMAL' | 'LOW' | 'MEDIUM' | 'HIGH';
}

/**
 * Image generation feature configuration.
 */
export interface GeminiImageConfig {
  /**
   * Aspect ratio of the generated image.
   *
   * @default model-selected
   */
  aspectRatio?:
    | '1:1'
    | '1:4'
    | '4:1'
    | '1:8'
    | '8:1'
    | '2:3'
    | '3:2'
    | '3:4'
    | '4:3'
    | '4:5'
    | '5:4'
    | '9:16'
    | '16:9'
    | '21:9';

  /**
   * Size of the generated image.
   *
   * @default '1K'
   */
  imageSize?: '512' | '1K' | '2K' | '4K';
}

/**
 * Media resolution setting for generation config.
 */
export type GeminiMediaResolution =
  | 'MEDIA_RESOLUTION_UNSPECIFIED'
  | 'MEDIA_RESOLUTION_LOW'
  | 'MEDIA_RESOLUTION_MEDIUM'
  | 'MEDIA_RESOLUTION_HIGH';

/**
 * Media resolution object used on individual content parts.
 */
export interface GeminiPartMediaResolution {
  /**
   * Tokenization quality used for the media part.
   */
  level: GeminiPartMediaResolutionLevel;
}

/**
 * Media resolution level used by `GeminiPartMediaResolution`.
 */
export type GeminiPartMediaResolutionLevel =
  | 'MEDIA_RESOLUTION_UNSPECIFIED'
  | 'MEDIA_RESOLUTION_LOW'
  | 'MEDIA_RESOLUTION_MEDIUM'
  | 'MEDIA_RESOLUTION_HIGH'
  | 'MEDIA_RESOLUTION_ULTRA_HIGH';

/**
 * OpenAPI-like schema used for structured input and output data.
 */
export interface GeminiSchema {
  /**
   * Schema data type.
   */
  type: GeminiSchemaType;

  /**
   * Data format.
   */
  format?: string;

  /**
   * Schema title.
   */
  title?: string;

  /**
   * Parameter or field description. Markdown may be used.
   */
  description?: string;

  /**
   * Whether the value may be null.
   */
  nullable?: boolean;

  /**
   * Possible string enum values.
   */
  enum?: string[];

  /**
   * Maximum number of array items.
   */
  maxItems?: string;

  /**
   * Minimum number of array items.
   */
  minItems?: string;

  /**
   * Object properties.
   */
  properties?: Record<string, GeminiSchema>;

  /**
   * Required object property names.
   */
  required?: string[];

  /**
   * Minimum number of object properties.
   */
  minProperties?: string;

  /**
   * Maximum number of object properties.
   */
  maxProperties?: string;

  /**
   * Minimum string length.
   */
  minLength?: string;

  /**
   * Maximum string length.
   */
  maxLength?: string;

  /**
   * Regular expression pattern for string values.
   */
  pattern?: string;

  /**
   * Root schema example value.
   */
  example?: JSONValue;

  /**
   * Subschemas where the value may validate against any item.
   */
  anyOf?: GeminiSchema[];

  /**
   * Non-standard property order hint used for response ordering.
   */
  propertyOrdering?: string[];

  /**
   * Documentation-only default value.
   */
  default?: JSONValue;

  /**
   * Schema for array elements.
   */
  items?: GeminiSchema;

  /**
   * Minimum numeric value.
   */
  minimum?: number;

  /**
   * Maximum numeric value.
   */
  maximum?: number;
}

/**
 * OpenAPI data type values supported by Gemini schemas.
 */
export type GeminiSchemaType =
  | 'TYPE_UNSPECIFIED'
  | 'STRING'
  | 'NUMBER'
  | 'INTEGER'
  | 'BOOLEAN'
  | 'ARRAY'
  | 'OBJECT'
  | 'NULL'
  | 'string'
  | 'number'
  | 'integer'
  | 'boolean'
  | 'array'
  | 'object'
  | 'null';

/**
 * Service tier of a Gemini generation request.
 *
 * @default 'unspecified'
 */
export type GeminiServiceTier = 'unspecified' | 'standard' | 'flex' | 'priority';
